framework: mocha
preRun:
     command:
        - npm install --engine-strict
preMerge:
  pattern:
    - "./test/*.cjs"
postMerge:
  pattern: 
    - "./test/*.cjs"
postRun:
     command:
        - node --version
configFile: mocharc.yml
version: 1.0
